shell = "zsh"

[plugins.zsh-functions]
local = "~/.config/zsh/lib"
use = ["*.zsh"]
apply = ["source"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-autosuggestions-conf]
inline = '''
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=245' 
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
'''

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zoxide]
inline = 'eval "$(zoxide init zsh)"'

[plugins.fzf]
github = "junegunn/fzf"
dir = "shell"
use = ["completion.zsh", "key-bindings.zsh"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.p]
github = "gumieri/p"
dir = "zsh"
use = ["*.zsh"]


















[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-syntax-colors]
inline = '''
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[comment]='fg=245'
ZSH_HIGHLIGHT_STYLES[alias]='fg=142,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=142,bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=142,bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=142,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=142,bold'
ZSH_HIGHLIGHT_STYLES[path]='fg=214'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=214'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=214,underline'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=109'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=109'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=208'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=208'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=167'
'''
